{% set name = "quantumflow" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quantumflow-{{ version }}.tar.gz
  sha256: 9a905110f302cbdd86783f0b7881e32c06102a1a5cc17d9b31fa44ea77c5429d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - decorator <5.0.0
    - importlib-metadata
    - matplotlib-base
    - networkx
    - numpy
    - opt-einsum
    - pillow !=9.1.0
    - python >=3.9
    - scipy <1.10.0
    - sympy >=1.6
    - typing_extensions >=4.1.1

test:
  imports:
    - quantumflow
  commands:
    - pip check
    - pytest quantumflow
  requires:
    - pip
    - pytest
  source_files:
    - quantumflow

about:
  home: https://github.com/gecrooks/quantumflow/
  summary: Cross compiler for gate based models of quantum computing
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
